const STORAGE_KEY = "projectdock.locale";

export const supportedLocales = [
  { code: "auto", label: "System" },
  { code: "zh-Hans", label: "简体中文" },
  { code: "zh-Hant", label: "繁體中文" },
  { code: "en", label: "English" },
  { code: "ja", label: "日本語" },
  { code: "ko", label: "한국어" },
  { code: "de", label: "Deutsch" },
  { code: "fr", label: "Français" },
  { code: "es", label: "Español" },
  { code: "pt-BR", label: "Português (Brasil)" },
  { code: "ru", label: "Русский" },
  { code: "ar", label: "العربية" },
];

const localeColumns = ["zh-Hant", "en", "ja", "ko", "de", "fr", "es", "pt-BR", "ru", "ar"];

// The Simplified Chinese source phrase is the stable key. Keeping all translations in
// one row makes missing-language checks deterministic and prevents partial locale files.
const rows = [
  ["本地项目总控台", "本機專案總控台", "Local project control center", "ローカルプロジェクト管制センター", "로컬 프로젝트 제어 센터", "Lokale Projektzentrale", "Centre de contrôle des projets locaux", "Centro de control de proyectos locales", "Central de projetos locais", "Локальный центр управления проектами", "مركز التحكم بالمشاريع المحلية"],
  ["ProjectDock 首页", "ProjectDock 首頁", "ProjectDock home", "ProjectDock ホーム", "ProjectDock 홈", "ProjectDock-Startseite", "Accueil ProjectDock", "Inicio de ProjectDock", "Início do ProjectDock", "Главная ProjectDock", "الصفحة الرئيسية لـ ProjectDock"],
  ["主导航", "主導覽", "Main navigation", "メインナビゲーション", "기본 탐색", "Hauptnavigation", "Navigation principale", "Navegación principal", "Navegação principal", "Основная навигация", "التنقل الرئيسي"],
  ["总览", "總覽", "Overview", "概要", "개요", "Übersicht", "Vue d’ensemble", "Resumen", "Visão geral", "Обзор", "نظرة عامة"],
  ["项目", "專案", "Projects", "プロジェクト", "프로젝트", "Projekte", "Projets", "Proyectos", "Projetos", "Проекты", "المشاريع"],
  ["端口", "連接埠", "Ports", "ポート", "포트", "Ports", "Ports", "Puertos", "Portas", "Порты", "المنافذ"],
  ["接口调试", "介面偵錯", "API workbench", "API デバッグ", "API 디버깅", "API-Debugging", "Débogage API", "Depuración de API", "Depuração de API", "Отладка API", "اختبار API"],
  ["操作审计", "操作稽核", "Audit log", "操作監査", "작업 감사", "Aktionsprotokoll", "Journal d’audit", "Registro de auditoría", "Log de auditoria", "Журнал аудита", "سجل التدقيق"],
  ["运行总览", "執行總覽", "Runtime overview", "稼働概要", "실행 개요", "Laufzeitübersicht", "Vue d’ensemble de l’exécution", "Resumen de ejecución", "Visão geral da execução", "Обзор работы", "نظرة عامة على التشغيل"],
  ["项目管理", "專案管理", "Project management", "プロジェクト管理", "프로젝트 관리", "Projektverwaltung", "Gestion des projets", "Gestión de proyectos", "Gerenciamento de projetos", "Управление проектами", "إدارة المشاريع"],
  ["端口监控", "連接埠監控", "Port monitoring", "ポート監視", "포트 모니터링", "Portüberwachung", "Surveillance des ports", "Supervisión de puertos", "Monitoramento de portas", "Мониторинг портов", "مراقبة المنافذ"],
  ["正在同步", "正在同步", "Syncing", "同期中", "동기화 중", "Synchronisierung", "Synchronisation", "Sincronizando", "Sincronizando", "Синхронизация", "جارٍ المزامنة"],
  ["同步失败", "同步失敗", "Sync failed", "同期に失敗", "동기화 실패", "Synchronisierung fehlgeschlagen", "Échec de la synchronisation", "Error de sincronización", "Falha na sincronização", "Ошибка синхронизации", "فشلت المزامنة"],
  ["立即刷新", "立即重新整理", "Refresh now", "今すぐ更新", "지금 새로고침", "Jetzt aktualisieren", "Actualiser", "Actualizar ahora", "Atualizar agora", "Обновить", "تحديث الآن"],
  ["数据已刷新", "資料已重新整理", "Data refreshed", "データを更新しました", "데이터를 새로고침했습니다", "Daten aktualisiert", "Données actualisées", "Datos actualizados", "Dados atualizados", "Данные обновлены", "تم تحديث البيانات"],
  ["AI 设置", "AI 設定", "AI settings", "AI 設定", "AI 설정", "KI-Einstellungen", "Réglages IA", "Ajustes de IA", "Configurações de IA", "Настройки ИИ", "إعدادات الذكاء الاصطناعي"],
  ["登记项目", "登記專案", "Register project", "プロジェクトを登録", "프로젝트 등록", "Projekt registrieren", "Enregistrer un projet", "Registrar proyecto", "Registrar projeto", "Зарегистрировать проект", "تسجيل مشروع"],
  ["编辑项目", "編輯專案", "Edit project", "プロジェクトを編集", "프로젝트 편집", "Projekt bearbeiten", "Modifier le projet", "Editar proyecto", "Editar projeto", "Изменить проект", "تعديل المشروع"],
  ["保存项目", "儲存專案", "Save project", "プロジェクトを保存", "프로젝트 저장", "Projekt speichern", "Enregistrer le projet", "Guardar proyecto", "Salvar projeto", "Сохранить проект", "حفظ المشروع"],
  ["扫描项目", "掃描專案", "Scan projects", "プロジェクトをスキャン", "프로젝트 스캔", "Projekte scannen", "Analyser les projets", "Escanear proyectos", "Verificar projetos", "Сканировать проекты", "فحص المشاريع"],
  ["接口调用", "介面呼叫", "API request", "API リクエスト", "API 요청", "API-Anfrage", "Requête API", "Solicitud de API", "Solicitação de API", "Запрос API", "طلب API"],
  ["保存 AI 设置", "儲存 AI 設定", "Save AI settings", "AI 設定を保存", "AI 설정 저장", "KI-Einstellungen speichern", "Enregistrer les réglages IA", "Guardar ajustes de IA", "Salvar configurações de IA", "Сохранить настройки ИИ", "حفظ إعدادات الذكاء الاصطناعي"],
  ["验证 AI 连接", "驗證 AI 連線", "Verify AI connection", "AI 接続を検証", "AI 연결 확인", "KI-Verbindung prüfen", "Vérifier la connexion IA", "Verificar conexión de IA", "Verificar conexão de IA", "Проверить подключение ИИ", "التحقق من اتصال الذكاء الاصطناعي"],
  ["安装 GitHub 项目", "安裝 GitHub 專案", "Install GitHub project", "GitHub プロジェクトをインストール", "GitHub 프로젝트 설치", "GitHub-Projekt installieren", "Installer le projet GitHub", "Instalar proyecto de GitHub", "Instalar projeto do GitHub", "Установить проект GitHub", "تثبيت مشروع GitHub"],
  ["已授权 · 已登记", "已授權 · 已登記", "Authorized · Registered", "許可済み · 登録済み", "권한 부여됨 · 등록됨", "Freigegeben · Registriert", "Autorisé · Enregistré", "Autorizado · Registrado", "Autorizado · Registrado", "Разрешено · Зарегистрировано", "مصرح · مسجل"],
  ["未声明端口", "未宣告連接埠", "No declared ports", "ポート未指定", "선언된 포트 없음", "Keine Ports angegeben", "Aucun port déclaré", "Sin puertos declarados", "Nenhuma porta declarada", "Порты не объявлены", "لا توجد منافذ معلنة"],
  ["本地操作", "本機操作", "Local action", "ローカル操作", "로컬 작업", "Lokale Aktion", "Action locale", "Acción local", "Ação local", "Локальное действие", "إجراء محلي"],
  ["删除项目", "刪除專案", "Remove project", "プロジェクトを削除", "프로젝트 삭제", "Projekt entfernen", "Supprimer le projet", "Eliminar proyecto", "Remover projeto", "Удалить проект", "إزالة المشروع"],
  ["运行指标", "執行指標", "Runtime metrics", "稼働指標", "실행 지표", "Laufzeitmetriken", "Indicateurs d’exécution", "Métricas de ejecución", "Métricas de execução", "Показатели работы", "مقاييس التشغيل"],
  ["已登记项目", "已登記專案", "Registered projects", "登録済みプロジェクト", "등록된 프로젝트", "Registrierte Projekte", "Projets enregistrés", "Proyectos registrados", "Projetos registrados", "Зарегистрированные проекты", "المشاريع المسجلة"],
  ["监听端口", "監聽連接埠", "Listening ports", "待受ポート", "수신 포트", "Lauschende Ports", "Ports en écoute", "Puertos en escucha", "Portas em escuta", "Прослушиваемые порты", "المنافذ المستمعة"],
  ["持久分配", "持久分配", "Persistent allocations", "永続割り当て", "영구 할당", "Dauerhafte Zuweisungen", "Attributions persistantes", "Asignaciones persistentes", "Alocações persistentes", "Постоянные назначения", "التخصيصات الدائمة"],
  ["最近同步", "最近同步", "Last sync", "最終同期", "최근 동기화", "Letzte Synchronisierung", "Dernière synchronisation", "Última sincronización", "Última sincronização", "Последняя синхронизация", "آخر مزامنة"],
  ["项目运行态", "專案執行狀態", "Project runtime", "プロジェクト稼働状況", "프로젝트 실행 상태", "Projektstatus", "État des projets", "Estado de proyectos", "Estado dos projetos", "Состояние проектов", "حالة تشغيل المشاريع"],
  ["从这里启动或停止已登记项目", "從這裡啟動或停止已登記專案", "Start or stop registered projects here", "登録済みプロジェクトをここから起動・停止", "여기에서 등록된 프로젝트를 시작하거나 중지합니다", "Registrierte Projekte hier starten oder stoppen", "Démarrez ou arrêtez les projets enregistrés ici", "Inicie o detenga proyectos registrados aquí", "Inicie ou pare projetos registrados aqui", "Запускайте и останавливайте проекты здесь", "ابدأ أو أوقف المشاريع المسجلة من هنا"],
  ["端口雷达", "連接埠雷達", "Port radar", "ポートレーダー", "포트 레이더", "Port-Radar", "Radar des ports", "Radar de puertos", "Radar de portas", "Радар портов", "رادار المنافذ"],
  ["最近操作", "最近操作", "Recent activity", "最近の操作", "최근 작업", "Letzte Aktivitäten", "Activité récente", "Actividad reciente", "Atividade recente", "Последние действия", "النشاط الأخير"],
  ["查看全部 →", "查看全部 →", "View all →", "すべて表示 →", "모두 보기 →", "Alle anzeigen →", "Tout afficher →", "Ver todo →", "Ver tudo →", "Показать все →", "عرض الكل ←"],
  ["独立本机模式", "獨立本機模式", "Standalone local mode", "スタンドアロンローカルモード", "독립 로컬 모드", "Eigenständiger lokaler Modus", "Mode local autonome", "Modo local autónomo", "Modo local independente", "Автономный локальный режим", "الوضع المحلي المستقل"],
  ["仅限 127.0.0.1", "僅限 127.0.0.1", "127.0.0.1 only", "127.0.0.1 のみ", "127.0.0.1 전용", "Nur 127.0.0.1", "127.0.0.1 uniquement", "Solo 127.0.0.1", "Somente 127.0.0.1", "Только 127.0.0.1", "127.0.0.1 فقط"],
  ["开机自动启动", "開機自動啟動", "Launch at login", "ログイン時に起動", "로그인 시 실행", "Bei Anmeldung starten", "Lancer à l’ouverture de session", "Abrir al iniciar sesión", "Abrir ao iniciar sessão", "Запускать при входе", "التشغيل عند تسجيل الدخول"],
  ["前往系统设置允许", "前往系統設定允許", "Allow in System Settings", "システム設定で許可", "시스템 설정에서 허용", "In Systemeinstellungen erlauben", "Autoriser dans Réglages Système", "Permitir en Ajustes del Sistema", "Permitir nos Ajustes do Sistema", "Разрешить в настройках системы", "السماح في إعدادات النظام"],
  ["已开启 · 登录后在后台运行", "已開啟 · 登入後在背景執行", "Enabled · runs in the background after login", "有効 · ログイン後にバックグラウンドで実行", "켜짐 · 로그인 후 백그라운드에서 실행", "Aktiviert · läuft nach Anmeldung im Hintergrund", "Activé · s’exécute en arrière-plan après connexion", "Activado · se ejecuta en segundo plano tras iniciar sesión", "Ativado · executa em segundo plano após iniciar sessão", "Включено · работает в фоне после входа", "مفعّل · يعمل في الخلفية بعد تسجيل الدخول"],
  ["已关闭", "已關閉", "Disabled", "無効", "꺼짐", "Deaktiviert", "Désactivé", "Desactivado", "Desativado", "Выключено", "معطّل"],
  ["状态暂不可用", "狀態暫不可用", "Status unavailable", "状態を取得できません", "상태를 사용할 수 없음", "Status nicht verfügbar", "État indisponible", "Estado no disponible", "Status indisponível", "Статус недоступен", "الحالة غير متاحة"],
  ["安装或发现本地项目", "安裝或探索本機專案", "Install or discover local projects", "ローカルプロジェクトのインストールと検出", "로컬 프로젝트 설치 또는 검색", "Lokale Projekte installieren oder erkennen", "Installer ou découvrir des projets locaux", "Instalar o descubrir proyectos locales", "Instalar ou descobrir projetos locais", "Установка и поиск локальных проектов", "تثبيت أو اكتشاف المشاريع المحلية"],
  ["GitHub 安装", "GitHub 安裝", "GitHub install", "GitHub からインストール", "GitHub 설치", "GitHub-Installation", "Installation GitHub", "Instalar desde GitHub", "Instalar do GitHub", "Установка с GitHub", "التثبيت من GitHub"],
  ["扫描本地项目", "掃描本機專案", "Scan local projects", "ローカルプロジェクトをスキャン", "로컬 프로젝트 스캔", "Lokale Projekte scannen", "Analyser les projets locaux", "Escanear proyectos locales", "Verificar projetos locais", "Сканировать локальные проекты", "فحص المشاريع المحلية"],
  ["选择文件夹", "選擇資料夾", "Choose folder", "フォルダを選択", "폴더 선택", "Ordner auswählen", "Choisir un dossier", "Elegir carpeta", "Escolher pasta", "Выбрать папку", "اختيار مجلد"],
  ["搜索项目", "搜尋專案", "Search projects", "プロジェクトを検索", "프로젝트 검색", "Projekte suchen", "Rechercher des projets", "Buscar proyectos", "Buscar projetos", "Поиск проектов", "البحث في المشاريع"],
  ["搜索名称、路径或来源", "搜尋名稱、路徑或來源", "Search name, path, or source", "名前・パス・ソースを検索", "이름, 경로 또는 소스 검색", "Name, Pfad oder Quelle suchen", "Rechercher par nom, chemin ou source", "Buscar nombre, ruta u origen", "Buscar nome, caminho ou origem", "Поиск по имени, пути или источнику", "البحث بالاسم أو المسار أو المصدر"],
  ["项目列表", "專案列表", "Project list", "プロジェクト一覧", "프로젝트 목록", "Projektliste", "Liste des projets", "Lista de proyectos", "Lista de projetos", "Список проектов", "قائمة المشاريع"],
  ["来源", "來源", "Source", "ソース", "소스", "Quelle", "Source", "Origen", "Origem", "Источник", "المصدر"],
  ["分配端口", "分配連接埠", "Allocated ports", "割り当てポート", "할당 포트", "Zugewiesene Ports", "Ports attribués", "Puertos asignados", "Portas alocadas", "Назначенные порты", "المنافذ المخصصة"],
  ["状态", "狀態", "Status", "状態", "상태", "Status", "État", "Estado", "Status", "Статус", "الحالة"],
  ["操作", "操作", "Actions", "操作", "작업", "Aktionen", "Actions", "Acciones", "Ações", "Действия", "الإجراءات"],
  ["日志", "日誌", "Logs", "ログ", "로그", "Protokolle", "Journaux", "Registros", "Logs", "Журналы", "السجلات"],
  ["编辑", "編輯", "Edit", "編集", "편집", "Bearbeiten", "Modifier", "Editar", "Editar", "Изменить", "تعديل"],
  ["删除", "刪除", "Remove", "削除", "삭제", "Entfernen", "Supprimer", "Eliminar", "Remover", "Удалить", "إزالة"],
  ["启动", "啟動", "Start", "起動", "시작", "Starten", "Démarrer", "Iniciar", "Iniciar", "Запустить", "بدء"],
  ["停止", "停止", "Stop", "停止", "중지", "Stoppen", "Arrêter", "Detener", "Parar", "Остановить", "إيقاف"],
  ["配置启动", "設定啟動", "Configure start", "起動を設定", "시작 구성", "Start konfigurieren", "Configurer le démarrage", "Configurar inicio", "Configurar início", "Настроить запуск", "إعداد التشغيل"],
  ["运行中", "執行中", "Running", "実行中", "실행 중", "Läuft", "En cours", "En ejecución", "Em execução", "Работает", "قيد التشغيل"],
  ["启动中", "啟動中", "Starting", "起動中", "시작 중", "Wird gestartet", "Démarrage", "Iniciando", "Iniciando", "Запускается", "جارٍ البدء"],
  ["停止中", "停止中", "Stopping", "停止中", "중지 중", "Wird gestoppt", "Arrêt", "Deteniendo", "Parando", "Останавливается", "جارٍ الإيقاف"],
  ["已停止", "已停止", "Stopped", "停止済み", "중지됨", "Gestoppt", "Arrêté", "Detenido", "Parado", "Остановлен", "متوقف"],
  ["外部运行", "外部執行", "External process", "外部実行", "외부 실행", "Externer Prozess", "Processus externe", "Proceso externo", "Processo externo", "Внешний процесс", "عملية خارجية"],
  ["端口冲突", "連接埠衝突", "Port conflict", "ポート競合", "포트 충돌", "Portkonflikt", "Conflit de port", "Conflicto de puerto", "Conflito de porta", "Конфликт порта", "تعارض المنفذ"],
  ["路径不可用", "路徑不可用", "Path unavailable", "パス利用不可", "경로 사용 불가", "Pfad nicht verfügbar", "Chemin indisponible", "Ruta no disponible", "Caminho indisponível", "Путь недоступен", "المسار غير متاح"],
  ["已登记 · 启动未接入", "已登記 · 啟動未接入", "Registered · start not configured", "登録済み · 起動未設定", "등록됨 · 시작 미구성", "Registriert · Start nicht konfiguriert", "Enregistré · démarrage non configuré", "Registrado · inicio sin configurar", "Registrado · início não configurado", "Зарегистрирован · запуск не настроен", "مسجل · التشغيل غير معد"],
  ["已归档", "已封存", "Archived", "アーカイブ済み", "보관됨", "Archiviert", "Archivé", "Archivado", "Arquivado", "В архиве", "مؤرشف"],
  ["手动", "手動", "Manual", "手動", "수동", "Manuell", "Manuel", "Manual", "Manual", "Вручную", "يدوي"],
  ["自动同步", "自動同步", "Auto sync", "自動同期", "자동 동기화", "Automatische Synchronisierung", "Synchronisation auto", "Sincronización automática", "Sincronização automática", "Автосинхронизация", "مزامنة تلقائية"],
  ["手动登记", "手動登記", "Manual registration", "手動登録", "수동 등록", "Manuell registriert", "Enregistrement manuel", "Registro manual", "Registro manual", "Ручная регистрация", "تسجيل يدوي"],
  ["筛选端口", "篩選連接埠", "Filter ports", "ポートを絞り込み", "포트 필터", "Ports filtern", "Filtrer les ports", "Filtrar puertos", "Filtrar portas", "Фильтр портов", "تصفية المنافذ"],
  ["端口、PID、进程名", "連接埠、PID、程序名稱", "Port, PID, process", "ポート、PID、プロセス名", "포트, PID, 프로세스 이름", "Port, PID, Prozess", "Port, PID, processus", "Puerto, PID, proceso", "Porta, PID, processo", "Порт, PID, процесс", "المنفذ أو PID أو العملية"],
  ["活跃分配", "活躍分配", "Active allocations", "アクティブ割り当て", "활성 할당", "Aktive Zuweisungen", "Attributions actives", "Asignaciones activas", "Alocações ativas", "Активные назначения", "التخصيصات النشطة"],
  ["临时预留", "臨時預留", "Temporary reservations", "一時予約", "임시 예약", "Temporäre Reservierungen", "Réservations temporaires", "Reservas temporales", "Reservas temporárias", "Временные резервы", "الحجوزات المؤقتة"],
  ["未分配监听", "未分配監聽", "Unassigned listeners", "未割り当て待受", "미할당 수신", "Nicht zugewiesene Listener", "Écoutes non attribuées", "Escuchas no asignadas", "Escutas não alocadas", "Неназначенные слушатели", "المستمعون غير المخصصين"],
  ["检查并持久分配", "檢查並持久分配", "Check and allocate", "確認して永続割り当て", "확인 후 영구 할당", "Prüfen und zuweisen", "Vérifier et attribuer", "Comprobar y asignar", "Verificar e alocar", "Проверить и назначить", "فحص وتخصيص"],
  ["选择项目", "選擇專案", "Select project", "プロジェクトを選択", "프로젝트 선택", "Projekt auswählen", "Choisir un projet", "Seleccionar proyecto", "Selecionar projeto", "Выбрать проект", "اختيار مشروع"],
  ["使用方", "使用方", "Owner", "使用者", "사용자", "Nutzer", "Responsable", "Responsable", "Responsável", "Владелец", "المالك"],
  ["空闲建议", "閒置建議", "Available suggestions", "空き候補", "사용 가능 제안", "Freie Vorschläge", "Suggestions disponibles", "Sugerencias disponibles", "Sugestões disponíveis", "Свободные варианты", "اقتراحات متاحة"],
  ["实时监听", "即時監聽", "Live listeners", "リアルタイム待受", "실시간 수신", "Live-Listener", "Écoutes en direct", "Escuchas en vivo", "Escutas em tempo real", "Активные слушатели", "المستمعون المباشرون"],
  ["当前预留", "目前預留", "Current reservations", "現在の予約", "현재 예약", "Aktuelle Reservierungen", "Réservations actuelles", "Reservas actuales", "Reservas atuais", "Текущие резервы", "الحجوزات الحالية"],
  ["创建短时预留", "建立短時預留", "Create reservation", "一時予約を作成", "임시 예약 생성", "Reservierung erstellen", "Créer une réservation", "Crear reserva", "Criar reserva", "Создать резерв", "إنشاء حجز"],
  ["有效期", "有效期", "Duration", "有効期間", "유효 기간", "Dauer", "Durée", "Duración", "Duração", "Срок", "المدة"],
  ["1 小时", "1 小時", "1 hour", "1 時間", "1시간", "1 Stunde", "1 heure", "1 hora", "1 hora", "1 час", "ساعة واحدة"],
  ["4 小时", "4 小時", "4 hours", "4 時間", "4시간", "4 Stunden", "4 heures", "4 horas", "4 horas", "4 часа", "4 ساعات"],
  ["12 小时", "12 小時", "12 hours", "12 時間", "12시간", "12 Stunden", "12 heures", "12 horas", "12 horas", "12 часов", "12 ساعة"],
  ["24 小时", "24 小時", "24 hours", "24 時間", "24시간", "24 Stunden", "24 heures", "24 horas", "24 horas", "24 часа", "24 ساعة"],
  ["构造请求", "建立請求", "Build request", "リクエストを作成", "요청 구성", "Anfrage erstellen", "Construire la requête", "Crear solicitud", "Montar requisição", "Создать запрос", "إنشاء الطلب"],
  ["发送请求", "傳送請求", "Send request", "リクエストを送信", "요청 보내기", "Anfrage senden", "Envoyer la requête", "Enviar solicitud", "Enviar requisição", "Отправить запрос", "إرسال الطلب"],
  ["响应", "回應", "Response", "レスポンス", "응답", "Antwort", "Réponse", "Respuesta", "Resposta", "Ответ", "الاستجابة"],
  ["仅回环地址", "僅回環位址", "Loopback only", "ループバックのみ", "루프백 전용", "Nur Loopback", "Boucle locale uniquement", "Solo loopback", "Somente loopback", "Только loopback", "العنوان المحلي فقط"],
  ["刷新审计", "重新整理稽核", "Refresh audit", "監査を更新", "감사 새로고침", "Audit aktualisieren", "Actualiser l’audit", "Actualizar auditoría", "Atualizar auditoria", "Обновить аудит", "تحديث التدقيق"],
  ["时间", "時間", "Time", "時刻", "시간", "Zeit", "Heure", "Hora", "Hora", "Время", "الوقت"],
  ["结果", "結果", "Result", "結果", "결과", "Ergebnis", "Résultat", "Resultado", "Resultado", "Результат", "النتيجة"],
  ["成功", "成功", "Success", "成功", "성공", "Erfolgreich", "Réussi", "Correcto", "Sucesso", "Успешно", "نجاح"],
  ["失败", "失敗", "Failed", "失敗", "실패", "Fehlgeschlagen", "Échec", "Error", "Falha", "Ошибка", "فشل"],
  ["取消", "取消", "Cancel", "キャンセル", "취소", "Abbrechen", "Annuler", "Cancelar", "Cancelar", "Отмена", "إلغاء"],
  ["关闭", "關閉", "Close", "閉じる", "닫기", "Schließen", "Fermer", "Cerrar", "Fechar", "Закрыть", "إغلاق"],
  ["返回", "返回", "Back", "戻る", "뒤로", "Zurück", "Retour", "Volver", "Voltar", "Назад", "رجوع"],
  ["确认", "確認", "Confirm", "確認", "확인", "Bestätigen", "Confirmer", "Confirmar", "Confirmar", "Подтвердить", "تأكيد"],
  ["请确认操作", "請確認操作", "Confirm action", "操作を確認", "작업 확인", "Aktion bestätigen", "Confirmer l’action", "Confirmar acción", "Confirmar ação", "Подтвердите действие", "تأكيد الإجراء"],
  ["AI 模型配置", "AI 模型設定", "AI model configuration", "AI モデル設定", "AI 모델 설정", "KI-Modellkonfiguration", "Configuration du modèle IA", "Configuración del modelo de IA", "Configuração do modelo de IA", "Настройка модели ИИ", "إعداد نموذج الذكاء الاصطناعي"],
  ["模型供应商", "模型供應商", "Model provider", "モデルプロバイダー", "모델 공급자", "Modellanbieter", "Fournisseur du modèle", "Proveedor del modelo", "Provedor do modelo", "Поставщик модели", "مزود النموذج"],
  ["模型名称", "模型名稱", "Model name", "モデル名", "모델 이름", "Modellname", "Nom du modèle", "Nombre del modelo", "Nome do modelo", "Название модели", "اسم النموذج"],
  ["本机模型", "本機模型", "Local model", "ローカルモデル", "로컬 모델", "Lokales Modell", "Modèle local", "Modelo local", "Modelo local", "Локальная модель", "نموذج محلي"],
  ["自定义兼容接口", "自訂相容介面", "Custom compatible endpoint", "カスタム互換エンドポイント", "사용자 지정 호환 엔드포인트", "Benutzerdefinierter kompatibler Endpunkt", "Point d’accès compatible personnalisé", "Endpoint compatible personalizado", "Endpoint compatível personalizado", "Пользовательский совместимый адрес", "نقطة نهاية متوافقة مخصصة"],
  ["API 密钥", "API 金鑰", "API key", "API キー", "API 키", "API-Schlüssel", "Clé API", "Clave API", "Chave de API", "Ключ API", "مفتاح API"],
  ["保存并验证连接", "儲存並驗證連線", "Save and verify", "保存して接続を確認", "저장 후 연결 확인", "Speichern und prüfen", "Enregistrer et vérifier", "Guardar y verificar", "Salvar e verificar", "Сохранить и проверить", "حفظ والتحقق"],
  ["正在读取配置…", "正在讀取設定…", "Loading configuration…", "設定を読み込み中…", "구성을 불러오는 중…", "Konfiguration wird geladen…", "Chargement de la configuration…", "Cargando configuración…", "Carregando configuração…", "Загрузка конфигурации…", "جارٍ تحميل الإعدادات…"],
  ["正在检查 AI 配置…", "正在檢查 AI 設定…", "Checking AI configuration…", "AI 設定を確認中…", "AI 구성을 확인하는 중…", "KI-Konfiguration wird geprüft…", "Vérification de la configuration IA…", "Comprobando la configuración de IA…", "Verificando a configuração de IA…", "Проверка конфигурации ИИ…", "جارٍ التحقق من إعدادات الذكاء الاصطناعي…"],
  ["AI 模型连接验证成功", "AI 模型連線驗證成功", "AI model connection verified", "AI モデル接続を確認しました", "AI 모델 연결 확인 성공", "KI-Modellverbindung bestätigt", "Connexion au modèle IA vérifiée", "Conexión con el modelo de IA verificada", "Conexão com o modelo de IA verificada", "Подключение к модели ИИ подтверждено", "تم التحقق من اتصال نموذج الذكاء الاصطناعي"],
  ["从 GitHub 安装项目", "從 GitHub 安裝專案", "Install project from GitHub", "GitHub からプロジェクトをインストール", "GitHub에서 프로젝트 설치", "Projekt von GitHub installieren", "Installer un projet depuis GitHub", "Instalar proyecto desde GitHub", "Instalar projeto do GitHub", "Установить проект с GitHub", "تثبيت مشروع من GitHub"],
  ["GitHub 仓库网址", "GitHub 儲存庫網址", "GitHub repository URL", "GitHub リポジトリ URL", "GitHub 저장소 URL", "GitHub-Repository-URL", "URL du dépôt GitHub", "URL del repositorio GitHub", "URL do repositório GitHub", "URL репозитория GitHub", "رابط مستودع GitHub"],
  ["项目安装目录", "專案安裝目錄", "Project install directory", "プロジェクトのインストール先", "프로젝트 설치 디렉터리", "Projekt-Installationsordner", "Dossier d’installation du projet", "Directorio de instalación", "Diretório de instalação", "Каталог установки проекта", "دليل تثبيت المشروع"],
  ["选择…", "選擇…", "Choose…", "選択…", "선택…", "Auswählen…", "Choisir…", "Elegir…", "Escolher…", "Выбрать…", "اختيار…"],
  ["配置 AI", "設定 AI", "Configure AI", "AI を設定", "AI 구성", "KI konfigurieren", "Configurer l’IA", "Configurar IA", "Configurar IA", "Настроить ИИ", "إعداد الذكاء الاصطناعي"],
  ["安装并登记", "安裝並登記", "Install and register", "インストールして登録", "설치 및 등록", "Installieren und registrieren", "Installer et enregistrer", "Instalar y registrar", "Instalar e registrar", "Установить и зарегистрировать", "تثبيت وتسجيل"],
  ["扫描可管理项目", "掃描可管理專案", "Scan manageable projects", "管理可能なプロジェクトをスキャン", "관리 가능한 프로젝트 스캔", "Verwaltbare Projekte scannen", "Analyser les projets gérables", "Escanear proyectos gestionables", "Verificar projetos gerenciáveis", "Сканировать управляемые проекты", "فحص المشاريع القابلة للإدارة"],
  ["扫描父目录", "掃描父目錄", "Parent directory to scan", "スキャンする親フォルダ", "스캔할 상위 디렉터리", "Zu scannender übergeordneter Ordner", "Dossier parent à analyser", "Directorio principal para escanear", "Diretório pai para verificar", "Родительский каталог", "الدليل الأب للفحص"],
  ["开始扫描", "開始掃描", "Start scan", "スキャン開始", "스캔 시작", "Scan starten", "Lancer l’analyse", "Iniciar escaneo", "Iniciar verificação", "Начать сканирование", "بدء الفحص"],
  ["导入所选项目", "匯入所選專案", "Import selected projects", "選択したプロジェクトを読み込む", "선택한 프로젝트 가져오기", "Ausgewählte Projekte importieren", "Importer les projets sélectionnés", "Importar proyectos seleccionados", "Importar projetos selecionados", "Импортировать выбранные проекты", "استيراد المشاريع المحددة"],
  ["仅移除登记", "僅移除登記", "Remove registration only", "登録のみ削除", "등록만 삭제", "Nur Registrierung entfernen", "Supprimer uniquement l’enregistrement", "Eliminar solo el registro", "Remover apenas o registro", "Удалить только регистрацию", "إزالة التسجيل فقط"],
  ["彻底卸载项目", "徹底解除安裝專案", "Completely uninstall project", "プロジェクトを完全に削除", "프로젝트 완전 제거", "Projekt vollständig deinstallieren", "Désinstaller complètement le projet", "Desinstalar proyecto por completo", "Desinstalar projeto completamente", "Полностью удалить проект", "إلغاء تثبيت المشروع بالكامل"],
  ["此操作不可撤销", "此操作無法復原", "This action cannot be undone", "この操作は取り消せません", "이 작업은 취소할 수 없습니다", "Diese Aktion kann nicht rückgängig gemacht werden", "Cette action est irréversible", "Esta acción no se puede deshacer", "Esta ação não pode ser desfeita", "Это действие необратимо", "لا يمكن التراجع عن هذا الإجراء"],
  ["项目名称确认", "專案名稱確認", "Confirm project name", "プロジェクト名を確認", "프로젝트 이름 확인", "Projektname bestätigen", "Confirmer le nom du projet", "Confirmar nombre del proyecto", "Confirmar nome do projeto", "Подтвердите имя проекта", "تأكيد اسم المشروع"],
  ["彻底卸载并删除全部内容", "徹底解除安裝並刪除全部內容", "Uninstall and delete all content", "完全にアンインストールしてすべて削除", "완전히 제거하고 모든 콘텐츠 삭제", "Vollständig deinstallieren und alle Inhalte löschen", "Désinstaller et supprimer tout le contenu", "Desinstalar y eliminar todo el contenido", "Desinstalar e excluir todo o conteúdo", "Удалить проект и всё содержимое", "إلغاء التثبيت وحذف جميع المحتويات"],
  ["运行日志", "執行日誌", "Runtime logs", "実行ログ", "실행 로그", "Laufzeitprotokolle", "Journaux d’exécution", "Registros de ejecución", "Logs de execução", "Журналы работы", "سجلات التشغيل"],
  ["无法连接本地控制台", "無法連線本機控制台", "Unable to connect to local console", "ローカルコンソールに接続できません", "로컬 콘솔에 연결할 수 없음", "Keine Verbindung zur lokalen Konsole", "Impossible de se connecter à la console locale", "No se puede conectar con la consola local", "Não foi possível conectar ao console local", "Не удалось подключиться к локальной консоли", "تعذر الاتصال بوحدة التحكم المحلية"],
  ["重新连接", "重新連線", "Reconnect", "再接続", "다시 연결", "Erneut verbinden", "Se reconnecter", "Volver a conectar", "Reconectar", "Подключиться снова", "إعادة الاتصال"],
  ["语言", "語言", "Language", "言語", "언어", "Sprache", "Langue", "Idioma", "Idioma", "Язык", "اللغة"],
  ["跟随系统", "跟隨系統", "Follow system", "システム設定に従う", "시스템 설정 따르기", "Systemsprache verwenden", "Suivre le système", "Seguir el sistema", "Seguir o sistema", "Как в системе", "اتباع النظام"],
  ["刚刚", "剛剛", "Just now", "たった今", "방금", "Gerade eben", "À l’instant", "Ahora mismo", "Agora mesmo", "Только что", "الآن"],
  ["未知", "未知", "Unknown", "不明", "알 수 없음", "Unbekannt", "Inconnu", "Desconocido", "Desconhecido", "Неизвестно", "غير معروف"],
  ["暂无操作记录", "暫無操作記錄", "No activity yet", "操作履歴はありません", "작업 기록 없음", "Noch keine Aktivitäten", "Aucune activité", "Aún no hay actividad", "Nenhuma atividade ainda", "Действий пока нет", "لا يوجد نشاط بعد"],
  ["暂无有效预留", "暫無有效預留", "No active reservations", "有効な予約はありません", "활성 예약 없음", "Keine aktiven Reservierungen", "Aucune réservation active", "No hay reservas activas", "Nenhuma reserva ativa", "Нет активных резервов", "لا توجد حجوزات نشطة"],
  ["没有匹配的可启动项目", "沒有符合的可啟動專案", "No matching startable projects", "一致する起動可能なプロジェクトはありません", "일치하는 시작 가능 프로젝트 없음", "Keine passenden startbaren Projekte", "Aucun projet démarrable correspondant", "No hay proyectos iniciables coincidentes", "Nenhum projeto inicializável correspondente", "Нет подходящих запускаемых проектов", "لا توجد مشاريع قابلة للتشغيل مطابقة"],
  ["没有匹配的监听端口", "沒有符合的監聽連接埠", "No matching listening ports", "一致する待受ポートはありません", "일치하는 수신 포트 없음", "Keine passenden lauschenden Ports", "Aucun port en écoute correspondant", "No hay puertos en escucha coincidentes", "Nenhuma porta em escuta correspondente", "Нет подходящих прослушиваемых портов", "لا توجد منافذ استماع مطابقة"],
  ["本地接口调用完成", "本機介面呼叫完成", "Local API request completed", "ローカル API リクエストが完了しました", "로컬 API 요청 완료", "Lokale API-Anfrage abgeschlossen", "Requête API locale terminée", "Solicitud API local completada", "Requisição de API local concluída", "Локальный API-запрос завершён", "اكتمل طلب API المحلي"],
  ["端口检查通过并已预留", "連接埠檢查通過並已預留", "Port checked and reserved", "ポートを確認して予約しました", "포트 확인 및 예약 완료", "Port geprüft und reserviert", "Port vérifié et réservé", "Puerto comprobado y reservado", "Porta verificada e reservada", "Порт проверен и зарезервирован", "تم فحص المنفذ وحجزه"],
  ["项目登记已保存", "專案登記已儲存", "Project registration saved", "プロジェクト登録を保存しました", "프로젝트 등록 저장됨", "Projektregistrierung gespeichert", "Enregistrement du projet sauvegardé", "Registro del proyecto guardado", "Registro do projeto salvo", "Регистрация проекта сохранена", "تم حفظ تسجيل المشروع"],
  ["请至少选择一个可管理项目", "請至少選擇一個可管理專案", "Select at least one manageable project", "管理可能なプロジェクトを1つ以上選択してください", "관리 가능한 프로젝트를 하나 이상 선택하세요", "Mindestens ein verwaltbares Projekt auswählen", "Sélectionnez au moins un projet gérable", "Seleccione al menos un proyecto gestionable", "Selecione pelo menos um projeto gerenciável", "Выберите хотя бы один управляемый проект", "اختر مشروعًا واحدًا قابلاً للإدارة على الأقل"],
  ["端口使用协议", "連接埠使用協議", "Port usage protocol", "ポート使用プロトコル", "포트 사용 프로토콜", "Portnutzungsprotokoll", "Protocole d’utilisation des ports", "Protocolo de uso de puertos", "Protocolo de uso de portas", "Протокол использования портов", "بروتوكول استخدام المنافذ"],
  ["已同步", "已同步", "Synced", "同期済み", "동기화됨", "Synchronisiert", "Synchronisé", "Sincronizado", "Sincronizado", "Синхронизировано", "تمت المزامنة"],
  ["{running} 个运行 · {ignored} 个已忽略", "{running} 個執行中 · {ignored} 個已忽略", "{running} running · {ignored} ignored", "{running} 件実行中 · {ignored} 件無視", "{running}개 실행 중 · {ignored}개 무시됨", "{running} aktiv · {ignored} ignoriert", "{running} en cours · {ignored} ignorés", "{running} en ejecución · {ignored} ignorados", "{running} em execução · {ignored} ignorados", "Работает: {running} · игнорируется: {ignored}", "قيد التشغيل {running} · متجاهل {ignored}"],
  ["本机唯一 TCP LISTEN", "本機唯一 TCP LISTEN", "Unique local TCP LISTEN ports", "ローカルで一意の TCP LISTEN", "로컬 고유 TCP LISTEN", "Eindeutige lokale TCP-LISTEN-Ports", "Ports TCP LISTEN locaux uniques", "Puertos TCP LISTEN locales únicos", "Portas TCP LISTEN locais únicas", "Уникальные локальные TCP LISTEN", "منافذ TCP LISTEN المحلية الفريدة"],
  ["{count} 个正在监听", "{count} 個正在監聽", "{count} listening", "{count} 件待受中", "{count}개 수신 중", "{count} lauschen", "{count} en écoute", "{count} escuchando", "{count} em escuta", "Слушает: {count}", "يستمع {count}"],
  ["自动刷新间隔 5 秒", "自動重新整理間隔 5 秒", "Auto-refresh every 5 seconds", "5 秒ごとに自動更新", "5초마다 자동 새로고침", "Automatische Aktualisierung alle 5 Sekunden", "Actualisation automatique toutes les 5 secondes", "Actualización automática cada 5 segundos", "Atualização automática a cada 5 segundos", "Автообновление каждые 5 секунд", "تحديث تلقائي كل 5 ثوانٍ"],
  ["还没有登记项目", "尚未登記專案", "No registered projects yet", "登録済みプロジェクトはありません", "아직 등록된 프로젝트가 없습니다", "Noch keine registrierten Projekte", "Aucun projet enregistré", "Aún no hay proyectos registrados", "Nenhum projeto registrado", "Зарегистрированных проектов пока нет", "لا توجد مشاريع مسجلة بعد"],
  ["先添加一个本地项目。", "先新增一個本機專案。", "Add a local project to get started.", "まずローカルプロジェクトを追加してください。", "먼저 로컬 프로젝트를 추가하세요.", "Fügen Sie zuerst ein lokales Projekt hinzu.", "Commencez par ajouter un projet local.", "Añada primero un proyecto local.", "Comece adicionando um projeto local.", "Сначала добавьте локальный проект.", "ابدأ بإضافة مشروع محلي."],
  ["持久分配及真实监听，5 秒刷新", "持久分配及真實監聽，每 5 秒重新整理", "Persistent allocations and live listeners, refreshed every 5 seconds", "永続割り当てと実待受を5秒ごとに更新", "영구 할당 및 실제 수신, 5초마다 새로고침", "Dauerhafte Zuweisungen und Live-Listener, alle 5 Sekunden aktualisiert", "Attributions persistantes et écoutes réelles, actualisées toutes les 5 secondes", "Asignaciones persistentes y escuchas reales, actualizadas cada 5 segundos", "Alocações persistentes e escutas reais, atualizadas a cada 5 segundos", "Постоянные назначения и активные слушатели, обновление каждые 5 секунд", "التخصيصات الدائمة والمستمعون المباشرون، تحديث كل 5 ثوانٍ"],
  ["当前没有持久端口分配", "目前沒有持久連接埠分配", "No persistent port allocations", "永続ポート割り当てはありません", "영구 포트 할당 없음", "Keine dauerhaften Portzuweisungen", "Aucune attribution de port persistante", "No hay asignaciones persistentes", "Nenhuma alocação persistente", "Нет постоянных назначений портов", "لا توجد تخصيصات منافذ دائمة"],
  ["结构化记录，不含敏感请求头", "結構化記錄，不含敏感請求標頭", "Structured records without sensitive headers", "機密ヘッダーを含まない構造化ログ", "민감한 헤더가 없는 구조화된 기록", "Strukturierte Protokolle ohne sensible Header", "Journaux structurés sans en-têtes sensibles", "Registros estructurados sin cabeceras sensibles", "Registros estruturados sem cabeçalhos sensíveis", "Структурированные записи без чувствительных заголовков", "سجلات منظمة دون رؤوس حساسة"],
  ["开发工具接入", "開發工具接入", "Developer tool integration", "開発ツール連携", "개발 도구 연동", "Entwicklertool-Integration", "Intégration des outils de développement", "Integración de herramientas de desarrollo", "Integração de ferramentas de desenvolvimento", "Интеграция инструментов разработки", "تكامل أدوات التطوير"],
  ["启动前先过端口门禁", "啟動前先通過連接埠門禁", "Pass the port gate before starting", "起動前にポートゲートを確認", "시작 전에 포트 검사를 통과하세요", "Vor dem Start die Portprüfung durchführen", "Validez le port avant de démarrer", "Compruebe el puerto antes de iniciar", "Verifique a porta antes de iniciar", "Перед запуском пройдите проверку порта", "تحقق من المنفذ قبل البدء"],
  ["检查", "檢查", "Check", "確認", "확인", "Prüfen", "Vérifier", "Comprobar", "Verificar", "Проверить", "فحص"],
  ["分配", "分配", "Allocate", "割り当て", "할당", "Zuweisen", "Attribuer", "Asignar", "Alocar", "Назначить", "تخصيص"],
  ["分配在项目停止后仍保留，直到显式取消。", "專案停止後仍保留分配，直到明確取消。", "Allocations remain after a project stops until explicitly removed.", "割り当てはプロジェクト停止後も明示的に解除するまで保持されます。", "할당은 프로젝트 중지 후에도 명시적으로 해제할 때까지 유지됩니다.", "Zuweisungen bleiben nach dem Projektstopp bestehen, bis sie ausdrücklich entfernt werden.", "Les attributions restent après l’arrêt du projet jusqu’à leur suppression explicite.", "Las asignaciones se conservan tras detener el proyecto hasta que se eliminen explícitamente.", "As alocações permanecem após a parada do projeto até serem removidas explicitamente.", "Назначения сохраняются после остановки проекта до явного удаления.", "تبقى التخصيصات بعد توقف المشروع حتى إزالتها صراحةً."],
  ["可粘贴 GitHub 仓库地址、扫描父目录，或直接添加现有文件夹。彻底卸载仅在二次确认后删除精确项目目录。", "可貼上 GitHub 儲存庫網址、掃描父目錄，或直接新增現有資料夾。徹底解除安裝僅在二次確認後刪除精確專案目錄。", "Paste a GitHub URL, scan a parent directory, or add an existing folder. Complete uninstall deletes the exact project directory only after a second confirmation.", "GitHub URL の貼り付け、親フォルダのスキャン、既存フォルダの追加ができます。完全削除は再確認後に正確なプロジェクトフォルダのみを削除します。", "GitHub URL을 붙여넣거나 상위 디렉터리를 스캔하거나 기존 폴더를 추가할 수 있습니다. 완전 제거는 이중 확인 후 정확한 프로젝트 디렉터리만 삭제합니다.", "GitHub-URL einfügen, übergeordneten Ordner scannen oder vorhandenen Ordner hinzufügen. Eine vollständige Deinstallation löscht nur nach zweiter Bestätigung den exakten Projektordner.", "Collez une URL GitHub, analysez un dossier parent ou ajoutez un dossier existant. La désinstallation complète ne supprime le dossier exact qu’après une seconde confirmation.", "Pegue una URL de GitHub, escanee un directorio principal o añada una carpeta. La desinstalación completa solo elimina el directorio exacto tras una segunda confirmación.", "Cole uma URL do GitHub, verifique um diretório pai ou adicione uma pasta. A desinstalação completa só exclui o diretório exato após uma segunda confirmação.", "Вставьте URL GitHub, просканируйте родительский каталог или добавьте папку. Полное удаление затрагивает точный каталог только после повторного подтверждения.", "الصق رابط GitHub أو افحص دليلاً أبًا أو أضف مجلدًا موجودًا. يحذف إلغاء التثبيت الكامل دليل المشروع المحدد فقط بعد تأكيد ثانٍ."],
  ["这里只显示路径可用且已接入安全启动方式的项目；登记与自动识别不会直接执行命令。", "此處僅顯示路徑可用且已接入安全啟動方式的專案；登記與自動識別不會直接執行命令。", "Only projects with an available path and a safe start method appear here. Registration and detection never execute commands directly.", "利用可能なパスと安全な起動方法を持つプロジェクトのみ表示します。登録や検出でコマンドが直接実行されることはありません。", "사용 가능한 경로와 안전한 시작 방법이 있는 프로젝트만 표시됩니다. 등록 및 감지는 명령을 직접 실행하지 않습니다.", "Hier erscheinen nur Projekte mit verfügbarem Pfad und sicherer Startmethode. Registrierung und Erkennung führen keine Befehle aus.", "Seuls les projets avec un chemin accessible et un démarrage sûr sont affichés. L’enregistrement et la détection n’exécutent aucune commande.", "Solo aparecen proyectos con una ruta disponible y un inicio seguro. El registro y la detección no ejecutan comandos.", "Apenas projetos com caminho disponível e início seguro aparecem. O registro e a detecção não executam comandos.", "Показаны только проекты с доступным путём и безопасным запуском. Регистрация и обнаружение не выполняют команды.", "تظهر فقط المشاريع ذات المسار المتاح وطريقة التشغيل الآمنة. لا ينفذ التسجيل أو الاكتشاف أوامر مباشرة."],
  ["添加具备明确启动方式的项目后，会在这里显示。", "新增具備明確啟動方式的專案後，會顯示於此。", "Projects with a defined start method will appear here.", "明確な起動方法を持つプロジェクトを追加するとここに表示されます。", "명확한 시작 방법이 있는 프로젝트를 추가하면 여기에 표시됩니다.", "Projekte mit definierter Startmethode erscheinen hier.", "Les projets disposant d’un démarrage défini apparaîtront ici.", "Los proyectos con un método de inicio definido aparecerán aquí.", "Projetos com uma forma de início definida aparecerão aqui.", "Здесь появятся проекты с настроенным запуском.", "ستظهر هنا المشاريع ذات طريقة التشغيل المحددة."],
  ["持久分配在项目未启动时同样占用资源池；真实 LISTEN 状态永远优先。", "持久分配在專案未啟動時同樣占用資源池；真實 LISTEN 狀態永遠優先。", "Persistent allocations occupy the pool even when a project is stopped; the real LISTEN state always takes priority.", "永続割り当ては停止中もプールを占有し、実際の LISTEN 状態が常に優先されます。", "영구 할당은 프로젝트가 중지되어도 풀을 차지하며 실제 LISTEN 상태가 항상 우선합니다.", "Dauerhafte Zuweisungen belegen den Pool auch bei gestoppten Projekten; der echte LISTEN-Status hat Vorrang.", "Les attributions persistantes occupent le pool même à l’arrêt ; l’état LISTEN réel reste prioritaire.", "Las asignaciones persistentes ocupan el grupo incluso con el proyecto detenido; el estado LISTEN real tiene prioridad.", "Alocações persistentes ocupam o pool mesmo com o projeto parado; o estado LISTEN real tem prioridade.", "Постоянные назначения занимают пул и при остановленном проекте; реальный LISTEN всегда приоритетен.", "تشغل التخصيصات الدائمة المجموعة حتى عند توقف المشروع؛ ولحالة LISTEN الفعلية الأولوية دائمًا."],
  ["未启动也占用", "未啟動也占用", "Reserved while stopped", "停止中も占有", "중지 중에도 예약", "Auch gestoppt reserviert", "Réservé même à l’arrêt", "Reservado aunque esté detenido", "Reservado mesmo parado", "Занят и при остановке", "محجوز حتى عند التوقف"],
  ["已有真实监听", "已有真實監聽", "Real listener active", "実待受あり", "실제 수신 활성", "Echter Listener aktiv", "Écoute réelle active", "Escucha real activa", "Escuta real ativa", "Есть реальный слушатель", "مستمع فعلي نشط"],
  ["到期自动释放", "到期自動釋放", "Released on expiry", "期限切れで自動解放", "만료 시 자동 해제", "Freigabe bei Ablauf", "Libéré à l’expiration", "Se libera al caducar", "Liberada ao expirar", "Освобождается по истечении", "يُحرر عند الانتهاء"],
  ["仅监控，不接管", "僅監控，不接管", "Monitor only", "監視のみ", "모니터링 전용", "Nur überwachen", "Surveillance uniquement", "Solo supervisar", "Somente monitorar", "Только мониторинг", "مراقبة فقط"],
  ["项目停止后仍保留，显式取消后才释放", "專案停止後仍保留，明確取消後才釋放", "Retained after stop; released only when explicitly removed", "停止後も保持され、明示的な解除でのみ解放", "중지 후에도 유지되며 명시적으로 해제할 때만 반환", "Bleibt nach Stopp erhalten; Freigabe nur nach Entfernen", "Conservé après l’arrêt ; libéré uniquement après suppression", "Se conserva tras detener; solo se libera al eliminar", "Mantida após parar; liberada apenas ao remover", "Сохраняется после остановки; освобождается только явно", "يبقى بعد التوقف ولا يُحرر إلا عند الإزالة صراحةً"],
  ["暂无持久分配；右侧选择项目和端口后即可加入资源池。", "暫無持久分配；在右側選擇專案和連接埠即可加入資源池。", "No persistent allocations. Select a project and port on the right to add one.", "永続割り当てはありません。右側でプロジェクトとポートを選択してください。", "영구 할당이 없습니다. 오른쪽에서 프로젝트와 포트를 선택하세요.", "Keine dauerhaften Zuweisungen. Rechts Projekt und Port auswählen.", "Aucune attribution persistante. Sélectionnez un projet et un port à droite.", "No hay asignaciones persistentes. Seleccione un proyecto y puerto a la derecha.", "Nenhuma alocação persistente. Selecione projeto e porta à direita.", "Постоянных назначений нет. Выберите проект и порт справа.", "لا توجد تخصيصات دائمة. اختر مشروعًا ومنفذًا من اليمين."],
  ["来自本机 lsof 的 TCP LISTEN；未分配监听也会单独统计", "來自本機 lsof 的 TCP LISTEN；未分配監聽也會單獨統計", "TCP LISTEN from local lsof; unassigned listeners are counted separately", "ローカル lsof の TCP LISTEN。未割り当て待受も別集計", "로컬 lsof의 TCP LISTEN이며 미할당 수신도 별도 집계", "TCP LISTEN aus lokalem lsof; nicht zugewiesene Listener werden separat gezählt", "TCP LISTEN issu de lsof local ; les écoutes non attribuées sont comptées séparément", "TCP LISTEN de lsof local; las escuchas no asignadas se cuentan aparte", "TCP LISTEN do lsof local; escutas não alocadas são contadas à parte", "TCP LISTEN из локального lsof; неназначенные слушатели считаются отдельно", "حالة TCP LISTEN من lsof المحلي؛ ويُحسب المستمعون غير المخصصين منفصلين"],
  ["进程", "程序", "Process", "プロセス", "프로세스", "Prozess", "Processus", "Proceso", "Processo", "Процесс", "العملية"],
  ["监听地址", "監聽位址", "Listen address", "待受アドレス", "수신 주소", "Lauschadresse", "Adresse d’écoute", "Dirección de escucha", "Endereço de escuta", "Адрес прослушивания", "عنوان الاستماع"],
  ["到期会自动失效", "到期會自動失效", "Expires automatically", "期限切れで自動失効", "만료 시 자동 종료", "Läuft automatisch ab", "Expire automatiquement", "Caduca automáticamente", "Expira automaticamente", "Истекает автоматически", "ينتهي تلقائيًا"],
  ["请求方法", "請求方法", "Request method", "リクエストメソッド", "요청 메서드", "Anfragemethode", "Méthode de requête", "Método de solicitud", "Método da requisição", "Метод запроса", "طريقة الطلب"],
  ["接口地址", "介面位址", "Endpoint URL", "エンドポイント URL", "엔드포인트 URL", "Endpunkt-URL", "URL du point d’accès", "URL del endpoint", "URL do endpoint", "URL точки доступа", "رابط نقطة النهاية"],
  ["请求正文", "請求本文", "Request body", "リクエスト本文", "요청 본문", "Anfragetext", "Corps de la requête", "Cuerpo de la solicitud", "Corpo da requisição", "Тело запроса", "نص الطلب"],
  ["Authorization、Cookie、代理头与非本机地址会被安全门禁拒绝。", "Authorization、Cookie、代理標頭與非本機位址會被安全門禁拒絕。", "Authorization, Cookie, proxy headers, and non-local addresses are rejected by the safety gate.", "Authorization、Cookie、プロキシヘッダー、非ローカルアドレスは安全ゲートで拒否されます。", "Authorization, Cookie, 프록시 헤더 및 비로컬 주소는 안전 검사에서 거부됩니다.", "Authorization, Cookie, Proxy-Header und nicht lokale Adressen werden abgewiesen.", "Authorization, Cookie, en-têtes proxy et adresses non locales sont refusés.", "Authorization, Cookie, cabeceras proxy y direcciones no locales se rechazan.", "Authorization, Cookie, cabeçalhos de proxy e endereços não locais são recusados.", "Authorization, Cookie, прокси-заголовки и нелокальные адреса отклоняются.", "ترفض بوابة الأمان رؤوس Authorization وCookie والوكيل والعناوين غير المحلية."],
  ["发送请求后在这里查看状态、耗时、响应头和正文。", "傳送請求後在此查看狀態、耗時、回應標頭和本文。", "Send a request to see status, timing, response headers, and body here.", "リクエスト送信後、状態・時間・ヘッダー・本文をここで確認できます。", "요청 후 상태, 시간, 응답 헤더 및 본문을 여기에서 확인하세요.", "Nach dem Senden erscheinen hier Status, Dauer, Header und Inhalt.", "Envoyez une requête pour afficher l’état, la durée, les en-têtes et le corps.", "Envíe una solicitud para ver estado, tiempo, cabeceras y cuerpo.", "Envie uma requisição para ver status, duração, cabeçalhos e corpo.", "После отправки здесь появятся статус, время, заголовки и тело.", "أرسل طلبًا لعرض الحالة والمدة ورؤوس الاستجابة والنص هنا."],
  ["最近 200 条本地操作。URL 查询参数与敏感响应头不会进入记录。", "最近 200 筆本機操作。URL 查詢參數與敏感回應標頭不會進入記錄。", "The latest 200 local actions. URL query parameters and sensitive response headers are excluded.", "直近200件のローカル操作。URL クエリと機密レスポンスヘッダーは記録されません。", "최근 200개 로컬 작업입니다. URL 쿼리와 민감한 응답 헤더는 기록되지 않습니다.", "Die letzten 200 lokalen Aktionen. URL-Parameter und sensible Antwort-Header werden ausgeschlossen.", "Les 200 dernières actions locales. Les paramètres URL et en-têtes sensibles sont exclus.", "Las últimas 200 acciones locales. Se excluyen parámetros URL y cabeceras sensibles.", "As 200 ações locais mais recentes. Parâmetros de URL e cabeçalhos sensíveis são excluídos.", "Последние 200 локальных действий. Параметры URL и чувствительные заголовки исключены.", "آخر 200 إجراء محلي. لا تُسجل معلمات URL أو رؤوس الاستجابة الحساسة."],
  ["还没有操作记录", "尚無操作記錄", "No activity yet", "操作履歴はありません", "작업 기록이 없습니다", "Noch keine Aktivitäten", "Aucune activité", "Aún no hay actividad", "Nenhuma atividade ainda", "Действий пока нет", "لا يوجد نشاط بعد"],
  ["登记项目、预留端口或调用接口后会在这里出现。", "登記專案、預留連接埠或呼叫介面後會顯示於此。", "Register a project, reserve a port, or call an API to create an entry.", "プロジェクト登録、ポート予約、API 呼び出し後に表示されます。", "프로젝트 등록, 포트 예약 또는 API 호출 후 여기에 표시됩니다.", "Nach Projektregistrierung, Portreservierung oder API-Aufruf erscheinen Einträge hier.", "Les entrées apparaissent après l’enregistrement d’un projet, la réservation d’un port ou un appel API.", "Las entradas aparecen al registrar un proyecto, reservar un puerto o llamar a una API.", "Entradas aparecem após registrar projeto, reservar porta ou chamar uma API.", "Записи появятся после регистрации проекта, резерва порта или вызова API.", "تظهر السجلات بعد تسجيل مشروع أو حجز منفذ أو استدعاء API."],
  ["用于分析 GitHub 项目的技术栈和人工安装步骤。API 密钥只保存到 macOS 钥匙串，不写入 ProjectDock 注册表或审计日志。", "用於分析 GitHub 專案的技術堆疊和人工安裝步驟。API 金鑰僅儲存於 macOS 鑰匙圈，不寫入 ProjectDock 登錄檔或稽核日誌。", "Used to analyze a GitHub project’s stack and manual installation steps. The API key is stored only in macOS Keychain, never in the registry or audit log.", "GitHub プロジェクトの技術構成と手動インストール手順を分析します。API キーは macOS キーチェーンにのみ保存されます。", "GitHub 프로젝트의 기술 스택과 수동 설치 단계를 분석합니다. API 키는 macOS 키체인에만 저장됩니다.", "Analysiert Technik und manuelle Installation eines GitHub-Projekts. Der API-Schlüssel liegt nur im macOS-Schlüsselbund.", "Analyse la pile technique et l’installation manuelle d’un projet GitHub. La clé API est stockée uniquement dans le trousseau macOS.", "Analiza la tecnología y los pasos de instalación manual. La clave API solo se guarda en el llavero de macOS.", "Analisa a tecnologia e a instalação manual. A chave de API fica somente nas Chaves do macOS.", "Анализирует стек и ручную установку GitHub-проекта. Ключ API хранится только в Связке ключей macOS.", "يُستخدم لتحليل تقنيات مشروع GitHub وخطوات تثبيته يدويًا. يُحفظ مفتاح API في سلسلة مفاتيح macOS فقط."],
  ["阿里云百炼（标准 API）", "阿里雲百煉（標準 API）", "Alibaba Model Studio (standard API)", "Alibaba Model Studio（標準 API）", "Alibaba Model Studio(표준 API)", "Alibaba Model Studio (Standard-API)", "Alibaba Model Studio (API standard)", "Alibaba Model Studio (API estándar)", "Alibaba Model Studio (API padrão)", "Alibaba Model Studio (стандартный API)", "Alibaba Model Studio (واجهة قياسية)"],
  ["阿里云百炼（Coding Plan）", "阿里雲百煉（Coding Plan）", "Alibaba Model Studio (Coding Plan)", "Alibaba Model Studio（Coding Plan）", "Alibaba Model Studio(Coding Plan)", "Alibaba Model Studio (Coding Plan)", "Alibaba Model Studio (Coding Plan)", "Alibaba Model Studio (Coding Plan)", "Alibaba Model Studio (Coding Plan)", "Alibaba Model Studio (Coding Plan)", "Alibaba Model Studio (خطة البرمجة)"],
  ["选择后自动填写对应接口；密钥必须由同一供应商签发", "選擇後自動填入對應介面；金鑰必須由同一供應商簽發", "Selecting a provider fills its endpoint automatically; the key must come from the same provider", "選択するとエンドポイントが自動入力されます。キーは同じプロバイダー発行のものを使用してください", "공급자를 선택하면 엔드포인트가 자동 입력되며 키도 같은 공급자에서 발급되어야 합니다", "Die Auswahl setzt den Endpunkt automatisch; der Schlüssel muss vom selben Anbieter stammen", "Le choix remplit automatiquement le point d’accès ; la clé doit venir du même fournisseur", "La selección completa el endpoint; la clave debe ser del mismo proveedor", "A seleção preenche o endpoint; a chave deve ser do mesmo provedor", "Адрес заполняется автоматически; ключ должен быть от того же поставщика", "يُملأ العنوان تلقائيًا؛ ويجب أن يصدر المفتاح من المزود نفسه"],
  ["兼容模型接口基础地址", "相容模型介面基礎位址", "Compatible model API base URL", "互換モデル API ベース URL", "호환 모델 API 기본 URL", "Basis-URL der kompatiblen Modell-API", "URL de base de l’API de modèle compatible", "URL base de API de modelo compatible", "URL base da API de modelo compatível", "Базовый URL совместимого API модели", "عنوان API الأساسي لنموذج متوافق"],
  ["只允许 HTTPS；本机模型可使用 127.0.0.1 / localhost 的 HTTP 地址", "僅允許 HTTPS；本機模型可使用 127.0.0.1 / localhost 的 HTTP 位址", "HTTPS only; local models may use HTTP on 127.0.0.1 or localhost", "HTTPS のみ。ローカルモデルは 127.0.0.1 / localhost の HTTP を使用できます", "HTTPS만 허용되며 로컬 모델은 127.0.0.1 또는 localhost의 HTTP를 사용할 수 있습니다", "Nur HTTPS; lokale Modelle dürfen HTTP auf 127.0.0.1 oder localhost verwenden", "HTTPS uniquement ; les modèles locaux peuvent utiliser HTTP sur 127.0.0.1 ou localhost", "Solo HTTPS; los modelos locales pueden usar HTTP en 127.0.0.1 o localhost", "Somente HTTPS; modelos locais podem usar HTTP em 127.0.0.1 ou localhost", "Только HTTPS; локальные модели могут использовать HTTP на 127.0.0.1 или localhost", "HTTPS فقط؛ ويمكن للنماذج المحلية استخدام HTTP على 127.0.0.1 أو localhost"],
  ["远程接口需要密钥；本机回环模型可留空", "遠端介面需要金鑰；本機回環模型可留空", "Remote endpoints require a key; local loopback models may leave it blank", "リモートにはキーが必要です。ローカルのループバックモデルは空欄にできます", "원격 엔드포인트에는 키가 필요하며 로컬 루프백 모델은 비워 둘 수 있습니다", "Remote Endpunkte benötigen einen Schlüssel; lokale Loopback-Modelle können leer bleiben", "Les points distants exigent une clé ; les modèles locaux peuvent laisser ce champ vide", "Los endpoints remotos requieren clave; los modelos locales pueden dejarla vacía", "Endpoints remotos exigem chave; modelos locais podem deixar em branco", "Удалённым адресам нужен ключ; для локальной модели поле можно оставить пустым", "تتطلب النقاط البعيدة مفتاحًا؛ ويمكن تركه فارغًا للنماذج المحلية"],
  ["ProjectDock 会浅克隆仓库、调用已配置的 AI 分析项目，再安全登记本地启动方式；不会自动执行依赖安装或模型生成的命令。", "ProjectDock 會淺層複製儲存庫、呼叫已設定的 AI 分析專案，再安全登記本機啟動方式；不會自動執行相依套件安裝或模型產生的命令。", "ProjectDock shallow-clones the repository, analyzes it with the configured AI, and safely registers local start methods. It never installs dependencies or runs model-generated commands automatically.", "ProjectDock はリポジトリを浅く複製し、設定済み AI で分析して安全な起動方法を登録します。依存関係や生成コマンドは自動実行しません。", "ProjectDock은 저장소를 얕게 복제하고 AI로 분석한 뒤 안전한 시작 방법을 등록합니다. 종속성 설치나 생성 명령은 자동 실행하지 않습니다.", "ProjectDock klont flach, analysiert mit der konfigurierten KI und registriert sichere Startmethoden. Abhängigkeiten oder generierte Befehle werden nie automatisch ausgeführt.", "ProjectDock clone superficiellement, analyse avec l’IA configurée et enregistre les démarrages sûrs. Il n’installe jamais les dépendances ni n’exécute les commandes générées.", "ProjectDock clona superficialmente, analiza con la IA y registra inicios seguros. Nunca instala dependencias ni ejecuta comandos generados.", "ProjectDock faz clone raso, analisa com a IA e registra formas seguras de início. Nunca instala dependências nem executa comandos gerados.", "ProjectDock делает неглубокий клон, анализирует через ИИ и регистрирует безопасный запуск. Зависимости и сгенерированные команды не выполняются автоматически.", "ينسخ ProjectDock المستودع بشكل سطحي ويحلله بالذكاء الاصطناعي ويسجل التشغيل الآمن. ولا يثبت الاعتماديات أو ينفذ أوامر مولدة تلقائيًا."],
  ["项目将安装到“安装目录/仓库名称”", "專案將安裝到「安裝目錄/儲存庫名稱」", "The project will be installed under “install directory/repository name”", "「インストール先/リポジトリ名」にインストールされます", "‘설치 디렉터리/저장소 이름’에 설치됩니다", "Installation unter „Installationsordner/Repository-Name“", "Installation dans « dossier d’installation/nom du dépôt »", "Se instalará en «directorio de instalación/nombre del repositorio»", "Será instalado em “diretório de instalação/nome do repositório”", "Проект будет установлен в «каталог/имя репозитория»", "سيُثبت المشروع ضمن «دليل التثبيت/اسم المستودع»"],
  ["请填写接口地址和模型名称。", "請填寫介面位址和模型名稱。", "Enter the endpoint URL and model name.", "エンドポイント URL とモデル名を入力してください。", "엔드포인트 URL과 모델 이름을 입력하세요.", "Endpunkt-URL und Modellname eingeben.", "Saisissez l’URL du point d’accès et le nom du modèle.", "Introduzca la URL del endpoint y el nombre del modelo.", "Informe a URL do endpoint e o nome do modelo.", "Введите URL и название модели.", "أدخل رابط نقطة النهاية واسم النموذج."],
  ["最多向下扫描 5 层，自动忽略依赖、构建产物、隐藏目录和符号链接。只勾选识别到安全启动方式的项目。", "最多向下掃描 5 層，自動忽略相依套件、建置產物、隱藏目錄和符號連結。僅勾選識別到安全啟動方式的專案。", "Scans up to 5 levels deep and ignores dependencies, build outputs, hidden directories, and symlinks. Only projects with a safe start method are selected.", "最大5階層をスキャンし、依存関係・ビルド成果物・隠しフォルダ・シンボリックリンクを除外します。安全な起動方法を持つプロジェクトのみ選択します。", "최대 5단계까지 스캔하며 종속성, 빌드 결과물, 숨김 디렉터리 및 심볼릭 링크를 무시합니다. 안전한 시작 방법이 있는 프로젝트만 선택합니다.", "Scannt bis zu 5 Ebenen und ignoriert Abhängigkeiten, Build-Ausgaben, versteckte Ordner und Symlinks. Nur Projekte mit sicherem Start werden ausgewählt.", "Analyse jusqu’à 5 niveaux en ignorant dépendances, sorties de build, dossiers cachés et liens symboliques. Seuls les projets démarrables en sécurité sont sélectionnés.", "Escanea hasta 5 niveles e ignora dependencias, resultados de compilación, directorios ocultos y enlaces. Solo selecciona proyectos con inicio seguro.", "Verifica até 5 níveis e ignora dependências, builds, diretórios ocultos e links simbólicos. Apenas projetos com início seguro são selecionados.", "Сканирует до 5 уровней, игнорируя зависимости, сборки, скрытые каталоги и ссылки. Выбираются только проекты с безопасным запуском.", "يفحص حتى 5 مستويات ويتجاهل الاعتماديات ومخرجات البناء والأدلة المخفية والروابط. يحدد فقط المشاريع ذات التشغيل الآمن."],
  ["选择一个父目录开始扫描。", "選擇一個父目錄開始掃描。", "Choose a parent directory to start scanning.", "親フォルダを選択してスキャンを開始してください。", "스캔을 시작할 상위 디렉터리를 선택하세요.", "Übergeordneten Ordner auswählen, um den Scan zu starten.", "Choisissez un dossier parent pour lancer l’analyse.", "Elija un directorio principal para iniciar el escaneo.", "Escolha um diretório pai para iniciar a verificação.", "Выберите родительский каталог для сканирования.", "اختر دليلاً أبًا لبدء الفحص."],
  ["正在开启…", "正在開啟…", "Enabling…", "有効化中…", "켜는 중…", "Wird aktiviert…", "Activation…", "Activando…", "Ativando…", "Включение…", "جارٍ التفعيل…"],
  ["正在关闭…", "正在關閉…", "Disabling…", "無効化中…", "끄는 중…", "Wird deaktiviert…", "Désactivation…", "Desactivando…", "Desativando…", "Выключение…", "جارٍ التعطيل…"],
  ["远程接口还需要 API 密钥。", "遠端介面仍需要 API 金鑰。", "The remote endpoint still needs an API key.", "リモートエンドポイントには API キーが必要です。", "원격 엔드포인트에는 API 키가 필요합니다.", "Der Remote-Endpunkt benötigt noch einen API-Schlüssel.", "Le point d’accès distant nécessite une clé API.", "El endpoint remoto requiere una clave API.", "O endpoint remoto precisa de uma chave de API.", "Удалённой точке доступа нужен ключ API.", "تحتاج نقطة النهاية البعيدة إلى مفتاح API."],
  ["配置已保存，正在验证真实模型连接…", "設定已儲存，正在驗證真實模型連線…", "Configuration saved; verifying the model connection…", "設定を保存しました。モデル接続を確認中…", "구성이 저장되었습니다. 모델 연결 확인 중…", "Konfiguration gespeichert; Modellverbindung wird geprüft…", "Configuration enregistrée ; vérification de la connexion…", "Configuración guardada; verificando la conexión…", "Configuração salva; verificando a conexão…", "Конфигурация сохранена; проверка подключения…", "تم حفظ الإعدادات؛ جارٍ التحقق من الاتصال…"],
  ["配置已保存但尚未验证；请点击“保存并验证连接”。", "設定已儲存但尚未驗證；請按一下「儲存並驗證連線」。", "Configuration saved but not verified; click “Save and verify”.", "設定は保存済みですが未確認です。「保存して接続を確認」を押してください。", "구성이 저장되었지만 확인되지 않았습니다. ‘저장 후 연결 확인’을 클릭하세요.", "Konfiguration gespeichert, aber nicht geprüft; „Speichern und prüfen“ wählen.", "Configuration enregistrée mais non vérifiée ; cliquez sur « Enregistrer et vérifier ».", "Configuración guardada sin verificar; pulse «Guardar y verificar».", "Configuração salva, mas não verificada; clique em “Salvar e verificar”.", "Конфигурация сохранена, но не проверена; нажмите «Сохранить и проверить».", "تم حفظ الإعدادات دون تحقق؛ انقر «حفظ والتحقق»."],
  ["没有发现带常见项目标记的目录。", "未發現帶常見專案標記的目錄。", "No directories with common project markers were found.", "一般的なプロジェクトマーカーを持つフォルダは見つかりませんでした。", "일반적인 프로젝트 표시가 있는 디렉터리를 찾지 못했습니다.", "Keine Ordner mit üblichen Projektmerkmalen gefunden.", "Aucun dossier avec des marqueurs de projet courants.", "No se encontraron directorios con marcadores de proyecto comunes.", "Nenhum diretório com marcadores comuns de projeto foi encontrado.", "Каталоги с типичными признаками проекта не найдены.", "لم يُعثر على أدلة تحمل علامات مشاريع شائعة."],
  ["结果已达到 250 个上限，请缩小扫描范围。", "結果已達 250 個上限，請縮小掃描範圍。", "The 250-result limit was reached; narrow the scan scope.", "250件の上限に達しました。スキャン範囲を狭めてください。", "결과가 250개 한도에 도달했습니다. 스캔 범위를 줄이세요.", "Das Limit von 250 Ergebnissen ist erreicht; Scanbereich einschränken.", "La limite de 250 résultats est atteinte ; réduisez la zone analysée.", "Se alcanzó el límite de 250 resultados; reduzca el alcance.", "O limite de 250 resultados foi atingido; reduza o escopo.", "Достигнут лимит 250 результатов; сузьте область сканирования.", "تم بلوغ حد 250 نتيجة؛ قلّص نطاق الفحص."],
  ["已管理", "已管理", "Managed", "管理済み", "관리됨", "Verwaltet", "Géré", "Gestionado", "Gerenciado", "Управляется", "مُدار"],
  ["未识别启动方式", "未識別啟動方式", "No start method detected", "起動方法を検出できません", "시작 방법이 감지되지 않음", "Keine Startmethode erkannt", "Aucun démarrage détecté", "No se detectó método de inicio", "Nenhuma forma de início detectada", "Способ запуска не определён", "لم تُكتشف طريقة تشغيل"],
  ["当前没有可显示的受管运行日志。", "目前沒有可顯示的受管執行日誌。", "No managed runtime logs are available.", "表示できる管理対象の実行ログはありません。", "표시할 관리형 실행 로그가 없습니다.", "Keine verwalteten Laufzeitprotokolle verfügbar.", "Aucun journal d’exécution géré disponible.", "No hay registros de ejecución gestionados.", "Não há logs de execução gerenciados.", "Нет доступных управляемых журналов.", "لا توجد سجلات تشغيل مُدارة متاحة."],
  ["Mac App Store 沙盒模式", "Mac App Store 沙盒模式", "Mac App Store sandbox mode", "Mac App Store サンドボックスモード", "Mac App Store 샌드박스 모드", "Mac-App-Store-Sandboxmodus", "Mode sandbox du Mac App Store", "Modo sandbox de Mac App Store", "Modo sandbox da Mac App Store", "Режим песочницы Mac App Store", "وضع عزل Mac App Store"],
  ["仅访问用户授权目录", "僅存取使用者授權的資料夾", "User-authorized folders only", "ユーザーが許可したフォルダのみ", "사용자가 허용한 폴더만", "Nur vom Benutzer freigegebene Ordner", "Dossiers autorisés par l’utilisateur uniquement", "Solo carpetas autorizadas por el usuario", "Somente pastas autorizadas pelo usuário", "Только папки, разрешённые пользователем", "مجلدات مصرح بها من المستخدم فقط"],
  ["目录授权", "資料夾授權", "Folder access", "フォルダアクセス", "폴더 액세스", "Ordnerzugriff", "Accès aux dossiers", "Acceso a carpetas", "Acesso a pastas", "Доступ к папкам", "الوصول إلى المجلدات"],
  ["安全作用域", "安全作用域", "Security scoped", "セキュリティスコープ", "보안 범위", "Sicherheitsbereich", "Accès sécurisé", "Ámbito seguro", "Escopo seguro", "Безопасная область", "نطاق آمن"],
  ["仅访问系统选择的目录", "僅存取透過系統選取的資料夾", "Only folders chosen in the system picker", "システムで選択したフォルダのみ", "시스템 선택기에서 선택한 폴더만", "Nur im Systemdialog gewählte Ordner", "Uniquement les dossiers choisis dans le sélecteur système", "Solo carpetas elegidas con el selector del sistema", "Somente pastas escolhidas no seletor do sistema", "Только папки из системного диалога", "المجلدات المختارة من النظام فقط"],
  ["没有匹配的已授权项目", "沒有符合的已授權專案", "No matching authorized projects", "一致する許可済みプロジェクトはありません", "일치하는 허용된 프로젝트가 없습니다", "Keine passenden autorisierten Projekte", "Aucun projet autorisé correspondant", "No hay proyectos autorizados coincidentes", "Nenhum projeto autorizado correspondente", "Нет подходящих разрешённых проектов", "لا توجد مشاريع مصرح بها مطابقة"],
  ["选择一个项目目录，即可安全登记和扫描。", "選擇專案資料夾，即可安全登記與掃描。", "Choose a project folder to register and scan it safely.", "プロジェクトフォルダを選択して安全に登録・スキャンします。", "프로젝트 폴더를 선택해 안전하게 등록하고 스캔하세요.", "Projektordner auswählen, um ihn sicher zu registrieren und zu scannen.", "Choisissez un dossier de projet pour l’enregistrer et l’analyser en sécurité.", "Elija una carpeta de proyecto para registrarla y escanearla de forma segura.", "Escolha uma pasta de projeto para registrar e verificar com segurança.", "Выберите папку проекта для безопасной регистрации и сканирования.", "اختر مجلد مشروع لتسجيله وفحصه بأمان."],
  ["查看已授权并登记的本地项目", "查看已授權並登記的本機專案", "View authorized and registered local projects", "許可・登録済みのローカルプロジェクトを表示", "허용되고 등록된 로컬 프로젝트 보기", "Autorisierte und registrierte lokale Projekte anzeigen", "Voir les projets locaux autorisés et enregistrés", "Ver proyectos locales autorizados y registrados", "Ver projetos locais autorizados e registrados", "Просмотр разрешённых и зарегистрированных проектов", "عرض المشاريع المحلية المصرح بها والمسجلة"],
  ["通过系统目录选择器授权后，可安全安装、扫描和登记项目。", "透過系統資料夾選取器授權後，可安全安裝、掃描與登記專案。", "Authorize a folder with the system picker to install, scan, and register projects safely.", "システムのフォルダ選択で許可し、安全にインストール・スキャン・登録します。", "시스템 폴더 선택기로 허용한 후 프로젝트를 안전하게 설치, 스캔, 등록하세요.", "Ordner im Systemdialog freigeben, um Projekte sicher zu installieren, zu scannen und zu registrieren.", "Autorisez un dossier avec le sélecteur système pour installer, analyser et enregistrer les projets en sécurité.", "Autorice una carpeta con el selector del sistema para instalar, escanear y registrar proyectos de forma segura.", "Autorize uma pasta com o seletor do sistema para instalar, verificar e registrar projetos com segurança.", "Разрешите папку в системном диалоге для безопасной установки, сканирования и регистрации.", "صرّح بمجلد عبر محدد النظام لتثبيت المشاريع وفحصها وتسجيلها بأمان."],
  ["通过系统目录选择器授权后，可扫描和登记本地项目。商店版不提供远程项目安装或 AI 功能。", "透過系統資料夾選取器授權後，可掃描與登記本機專案。商店版不提供遠端專案安裝或 AI 功能。", "Authorize a folder with the system picker to scan and register local projects. The Store edition does not provide remote project installation or AI features.", "システムのフォルダ選択で許可すると、ローカルプロジェクトをスキャンして登録できます。Store 版はリモートインストールと AI 機能を提供しません。", "시스템 폴더 선택기로 허용하면 로컬 프로젝트를 스캔하고 등록할 수 있습니다. Store 버전은 원격 프로젝트 설치와 AI 기능을 제공하지 않습니다.", "Geben Sie einen Ordner im Systemdialog frei, um lokale Projekte zu scannen und zu registrieren. Die Store-Version bietet keine Remote-Installation oder KI-Funktionen.", "Autorisez un dossier pour analyser et enregistrer les projets locaux. L’édition Store ne propose ni installation distante ni fonctions IA.", "Autorice una carpeta para escanear y registrar proyectos locales. La edición de la tienda no ofrece instalación remota ni funciones de IA.", "Autorize uma pasta para verificar e registrar projetos locais. A edição da loja não oferece instalação remota nem recursos de IA.", "Разрешите папку для сканирования и регистрации локальных проектов. Версия из Store не предоставляет удалённую установку или функции ИИ.", "صرّح بمجلد لفحص المشاريع المحلية وتسجيلها. لا يوفر إصدار المتجر تثبيت المشاريع عن بُعد أو ميزات الذكاء الاصطناعي."],
  ["这里显示已获目录授权并完成登记的项目；商店版不会执行项目启动命令。", "此處顯示已獲目錄授權並完成登記的專案；商店版不會執行專案啟動命令。", "Projects with authorized folders and completed registration appear here; the Store edition never runs project start commands.", "フォルダへのアクセスが許可され、登録済みのプロジェクトを表示します。Store 版はプロジェクトの起動コマンドを実行しません。", "폴더 접근 권한을 받고 등록된 프로젝트가 표시됩니다. Store 버전은 프로젝트 시작 명령을 실행하지 않습니다.", "Hier erscheinen Projekte mit Ordnerfreigabe und abgeschlossener Registrierung; die Store-Version führt keine Projektstartbefehle aus.", "Les projets dont le dossier est autorisé et l’enregistrement terminé apparaissent ici ; l’édition Store n’exécute aucune commande de démarrage.", "Aquí aparecen los proyectos con carpeta autorizada y registro completo; la edición de la tienda no ejecuta comandos de inicio.", "Aqui aparecem projetos com pasta autorizada e registro concluído; a edição da loja não executa comandos de inicialização.", "Здесь показаны проекты с разрешённой папкой и завершённой регистрацией; версия из Store не выполняет команды запуска.", "تظهر هنا المشاريع التي مُنح مجلدها الإذن واكتمل تسجيلها؛ ولا ينفذ إصدار المتجر أوامر تشغيل المشاريع."],
  ["ProjectDock 会通过 GitHub HTTPS 下载仓库 ZIP、调用已配置的 AI 分析项目，再登记到用户授权目录；不会自动执行依赖安装或模型生成的命令。", "ProjectDock 會透過 GitHub HTTPS 下載儲存庫 ZIP、呼叫已設定的 AI 分析專案，再登記至使用者授權目錄；不會自動執行相依套件安裝或模型產生的命令。", "ProjectDock downloads the repository ZIP over GitHub HTTPS, analyzes it with your configured AI, and registers it in an authorized folder. It never runs dependency installs or model-generated commands automatically.", "ProjectDock は GitHub HTTPS 経由でリポジトリ ZIP をダウンロードし、設定済み AI で分析して、許可済みフォルダに登録します。依存関係のインストールや AI 生成コマンドは自動実行しません。", "ProjectDock는 GitHub HTTPS로 저장소 ZIP을 내려받아 구성된 AI로 분석한 뒤 허용된 폴더에 등록합니다. 종속성 설치나 모델 생성 명령을 자동 실행하지 않습니다.", "ProjectDock lädt das Repository-ZIP über GitHub HTTPS, analysiert es mit der konfigurierten KI und registriert es in einem freigegebenen Ordner. Abhängigkeiten oder KI-Befehle werden nie automatisch ausgeführt.", "ProjectDock télécharge le ZIP du dépôt via GitHub HTTPS, l’analyse avec l’IA configurée, puis l’enregistre dans un dossier autorisé. Il n’exécute jamais automatiquement les dépendances ni les commandes générées.", "ProjectDock descarga el ZIP del repositorio mediante GitHub HTTPS, lo analiza con la IA configurada y lo registra en una carpeta autorizada. Nunca ejecuta automáticamente dependencias ni comandos generados.", "O ProjectDock baixa o ZIP do repositório por GitHub HTTPS, analisa-o com a IA configurada e o registra em uma pasta autorizada. Nunca executa automaticamente dependências ou comandos gerados.", "ProjectDock загружает ZIP репозитория по GitHub HTTPS, анализирует его настроенной моделью ИИ и регистрирует в разрешённой папке. Установка зависимостей и сгенерированные команды автоматически не запускаются.", "ينزّل ProjectDock ملف ZIP للمستودع عبر GitHub HTTPS ويحلله بالذكاء الاصطناعي المُعد ثم يسجله في مجلد مصرح به. ولا يشغّل تثبيت الاعتماديات أو الأوامر المولدة تلقائيًا."],
  ["正在调用本地接口…", "正在呼叫本機介面…", "Calling local API…", "ローカル API を呼び出し中…", "로컬 API 호출 중…", "Lokale API wird aufgerufen…", "Appel de l’API locale…", "Llamando a la API local…", "Chamando a API local…", "Вызов локального API…", "جارٍ استدعاء API المحلي…"],
];

const catalogs = Object.fromEntries(supportedLocales.filter(({ code }) => code !== "auto").map(({ code }) => [code, {}]));
for (const row of rows) {
  catalogs["zh-Hans"][row[0]] = row[0];
  localeColumns.forEach((locale, index) => { catalogs[locale][row[0]] = row[index + 1]; });
}

function normalizeLocale(value) {
  const locale = String(value || "").replaceAll("_", "-");
  if (/^zh-(TW|HK|MO|Hant)/i.test(locale)) return "zh-Hant";
  if (/^zh/i.test(locale)) return "zh-Hans";
  if (/^pt/i.test(locale)) return "pt-BR";
  const short = locale.split("-")[0].toLowerCase();
  return supportedLocales.some(({ code }) => code === short) ? short : "en";
}

export function getLocalePreference() {
  try { return localStorage.getItem(STORAGE_KEY) || "auto"; } catch { return "auto"; }
}

export function getLocale() {
  const preference = getLocalePreference();
  if (preference !== "auto") return normalizeLocale(preference);
  for (const locale of navigator.languages || [navigator.language]) {
    const normalized = normalizeLocale(locale);
    if (normalized) return normalized;
  }
  return "en";
}

export function getIntlLocale() {
  return { "zh-Hans": "zh-CN", "zh-Hant": "zh-TW", "pt-BR": "pt-BR" }[getLocale()] || getLocale();
}

export function setLocalePreference(locale) {
  if (!supportedLocales.some(({ code }) => code === locale)) return false;
  try { localStorage.setItem(STORAGE_KEY, locale); } catch { return false; }
  return true;
}

export function t(source, variables = {}) {
  let result = catalogs[getLocale()]?.[source] || catalogs.en[source] || source;
  for (const [name, value] of Object.entries(variables)) result = result.replaceAll(`{${name}}`, String(value));
  return result;
}

export function localizeDOM(root = document) {
  const locale = getLocale();
  document.documentElement.lang = getIntlLocale();
  document.documentElement.dir = locale === "ar" ? "rtl" : "ltr";
  document.title = `ProjectDock · ${t("本地项目总控台")}`;
  const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT);
  const nodes = [];
  while (walker.nextNode()) nodes.push(walker.currentNode);
  for (const node of nodes) {
    const original = node.nodeValue;
    const trimmed = original.trim();
    if (!trimmed) continue;
    const translated = t(trimmed);
    if (translated !== trimmed) node.nodeValue = original.replace(trimmed, translated);
  }
  root.querySelectorAll?.("[placeholder], [aria-label], [title]").forEach((element) => {
    for (const attribute of ["placeholder", "aria-label", "title"]) {
      const value = element.getAttribute(attribute);
      if (value) element.setAttribute(attribute, t(value));
    }
  });
}

export function localeCoverage() {
  return Object.fromEntries(Object.entries(catalogs).map(([locale, catalog]) => [locale, {
    translated: Object.keys(catalog).length,
    expected: rows.length,
    complete: Object.keys(catalog).length === rows.length,
  }]));
}
